dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - libcmocka-dev
      - rpm
      - valgrind

compiler:
  - clang
  - gcc

env:
  - TARGET=valgrind
  - TARGET=distcheck
  - TARGET=dist-srpm

matrix:
  exclude:
    - compiler: clang
      env: TARGET=dist-srpm

install: gem install ronn

before_script:
  - git fetch --unshallow
  - ./autogen.sh

script:
  - ./build-aux/travis-build.sh
  - ./build-aux/travis-deploy.sh
